// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Escolar.Data;

namespace Sistema_Escolar.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20230225210015_SistemaEscolar")]
    partial class SistemaEscolar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sistema_Escolar.Models.AlunosModel", b =>
                {
                    b.Property<int>("ID_ALUNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Codigo_Turma")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_TURMA")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Completo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_Cadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurmaCodigo_Turma")
                        .HasColumnType("int");

                    b.HasKey("ID_ALUNO");

                    b.HasIndex("TurmaCodigo_Turma");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Sistema_Escolar.Models.EscolaModel", b =>
                {
                    b.Property<int>("Codigo_Escola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome_Escola")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qtde_Alunos")
                        .HasColumnType("int");

                    b.Property<int>("Qtde_Turmas")
                        .HasColumnType("int");

                    b.HasKey("Codigo_Escola");

                    b.ToTable("Escolas");
                });

            modelBuilder.Entity("Sistema_Escolar.Models.TurmaModel", b =>
                {
                    b.Property<int>("Codigo_Turma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EscolaCodigo_Escola")
                        .HasColumnType("int");

                    b.Property<int>("ID_ESCOLA")
                        .HasColumnType("int");

                    b.Property<int>("ID_MATERIA")
                        .HasColumnType("int");

                    b.HasKey("Codigo_Turma");

                    b.HasIndex("EscolaCodigo_Escola");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Sistema_Escolar.Models.AlunosModel", b =>
                {
                    b.HasOne("Sistema_Escolar.Models.TurmaModel", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaCodigo_Turma");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Sistema_Escolar.Models.TurmaModel", b =>
                {
                    b.HasOne("Sistema_Escolar.Models.EscolaModel", "Escola")
                        .WithMany("Turmas")
                        .HasForeignKey("EscolaCodigo_Escola");

                    b.Navigation("Escola");
                });

            modelBuilder.Entity("Sistema_Escolar.Models.EscolaModel", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("Sistema_Escolar.Models.TurmaModel", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
